In [6]:
import  numpy as np
n=np.zeros((2,3))
print(n)
k=np.shape
print(k)
print(n.shape
)


[[0. 0. 0.]
 [0. 0. 0.]]
<function shape at 0x000002942C0AE8E0>
(2, 3)


In [12]:
#q1
n=np.ones((2,3))
print(n)
print(np.zeros((3,3)))
print(np.full((2,5),7))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


In [14]:
#q2
k=np.reshape(np.arange(0,4),(2,2))
print(k)
print(k*3)
print(k+7)
print(k*2)

[[0 1]
 [2 3]]
[[0 3]
 [6 9]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


In [53]:
n=np.reshape(np.arange(2,19,2),(3,3))
print(n)
k=np.reshape(np.arange(9,0,-1),(3,3))
print(k)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [58]:
#q4
n=np.reshape(np.arange(1,25,1),(6,-1))
print(n)
rf=n[0:2].copy() # n[0:2,:].copy();creating deepcopy of both else change swill be reflected
rl=n[4:6].copy()
print(rf)
print(n.shape)
n[0:2]=n[4:6]
n[4:6]=rf
print(n)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[1 2 3 4]
 [5 6 7 8]]
(6, 4)
[[17 18 19 20]
 [21 22 23 24]
 [ 9 10 11 12]
 [13 14 15 16]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [61]:
#q5
n1=np.array([2,3,5,7,11])
n2=np.array([13,17,19,23,29])
k=np.vstack((n1,n2))
print(k)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


In [71]:
#q6
n=np.reshape(np.array([2**i for i in range(0,6)]),(2,3)) #iterable object list via list comprehension
print(n)
k1=n.flatten()#deepcopy
print('\nk:',k1)
print('\nn:',n)
print('\nravel:',n.ravel())#shallowcopy
print('\nn:',n)

[[ 1  2  4]
 [ 8 16 32]]

k: [ 1  2  4  8 16 32]

n: [[ 1  2  4]
 [ 8 16 32]]

ravel: [ 1  2  4  8 16 32]

n: [[ 1  2  4]
 [ 8 16 32]]


In [80]:
import numpy as np

# The original array
arr = np.array([6, 9, 5, 1, 7, 5, 1, 0, 1, 5, 5, 0, 8, 9, 0, 7, 0, 7, 6, 5, 1, 1, 9, 5, 3, 8, 7, 9, 6, 3, 4, 5, 9, 7, 2, 7, 0, 2, 2, 6])

# Find unique elements and their counts
unique, counts = np.unique(arr, return_counts=True)
print(unique)
print(counts)
# Get the maximum count
max_count = np.max(counts)

# Find the elements with the maximum count
most_frequent = unique[counts == max_count]

print("Most Frequent Values:", most_frequent)
print("Frequency:", max_count)

[0 1 2 3 4 5 6 7 8 9]
[5 5 3 2 1 7 4 6 2 5]
Most Frequent Values: [5]
Frequency: 7


In [85]:
#q8
#n=np.array([1.1,2.2,3.3,4.4,5.5,6.6])
n=np.linspace(1.1, 6.6, num=6, endpoint=True, retstep=False, dtype=float)
print(n,'\n')
n=n.reshape((2,3))
k=n.astype(int)
print(k)

[1.1 2.2 3.3 4.4 5.5 6.6] 

[[1 2 3]
 [4 5 6]]


In [ ]:
'''In NumPy, linspace is a function that generates an array of evenly spaced numbers over a specified interval. It is particularly useful when you want a specific number of points between a start and stop value.

Syntax
python
Copy code
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
Parameters
start: The starting value of the sequence.
stop: The ending value of the sequence.
num: (Optional) Number of evenly spaced samples to generate. Default is 50.
endpoint: (Optional) If True (default), the stop value is included in the array. If False, it is excluded.
retstep: (Optional) If True, returns the step size in addition to the array.
dtype: (Optional) Specifies the data type of the resulting array.
Examples
1. Basic Usage
python
Copy code
import numpy as np

# Generate 5 evenly spaced numbers between 0 and 10
arr = np.linspace(0, 10, 5)
print(arr)
Output:

css
Copy code
[ 0.   2.5  5.   7.5 10. ]
2. Excluding the Endpoint
python
Copy code
arr = np.linspace(0, 10, 5, endpoint=False)
print(arr)
Output:

csharp
Copy code
[0.  2.  4.  6.  8.]
3. Returning the Step Size
python
Copy code
arr, step = np.linspace(0, 10, 5, retstep=True)
print("Array:", arr)
print("Step size:", step)
Output:

vbnet
Copy code
Array: [ 0.   2.5  5.   7.5 10. ]
Step size: 2.5
Key Points
Use Case: When you need a specific number of points between two values, rather than a specific step size (as with np.arange).
Endpoint Control: You can include or exclude the stop value using endpoint.
Return Step Size: You can get the spacing between points by enabling retstep.
Comparison with arange
arange: Generates values with a fixed step size.
linspace: Generates a fixed number of values between two bounds.
Example:
python
Copy code
np.arange(0, 10, 2)  # Step size is 2
# Output: [0 2 4 6 8]

np.linspace(0, 10, 5)  # 5 evenly spaced numbers
# Output: [ 0.   2.5  5.   7.5 10. ]
If you have a specific use case in mind, feel free to ask!
'''

In [86]:
#q9
import numpy as np

def format_2d_array(arr):
    # Convert input to NumPy array (if it's not already)
    arr = np.array(arr)
    
    # Find the maximum element in the array
    max_element = arr.max()
    
    # Determine the width of the largest element
    width = len(str(max_element))
    
    # Format the array
    formatted_rows = []
    for row in arr:
        # Format each element in the row to be right-aligned
        formatted_row = " ".join(f"{elem:>{width}}" for elem in row)
        formatted_rows.append(formatted_row)
    
    # Join all rows with newline characters
    return "\n".join(formatted_rows)

# Example usage
array = np.array([
    [1, 23, 456],
    [7890, 12, 34],
    [567, 890, 1234]
])

formatted_string = format_2d_array(array)
print(formatted_string)


   1   23  456
7890   12   34
 567  890 1234


In [97]:
n=np.reshape(np.arange(1,16),(3,5))
print(n,'\n')
print(n[2])
print(n[:,4])
print(n[0:2,:])
print(n[:,2:4])
print(n[1,4])
print(n[0:2,0],'\t',n[0:2,2],'\t',n[0:2,4])
#or
print(n[0:2,0:5:2])




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

[11 12 13 14 15]
[ 5 10 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4]
 [ 8  9]
 [13 14]]
10
[1 6] 	 [3 8] 	 [ 5 10]
[[ 1  3  5]
 [ 6  8 10]]


In [99]:
#q11
array1=np.array([[0,1],[2,3]])
array2=np.array([[4,5],[6,7]])
array3=np.vstack((array1,array2))
print(array3)
array4=np.hstack((array1,array2))
print(array4)
array5=np.vstack((array4,array4))
print(array5)
array6=np.hstack((array5,array5))
print(array6)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5 0 1 4 5]
 [2 3 6 7 2 3 6 7]
 [0 1 4 5 0 1 4 5]
 [2 3 6 7 2 3 6 7]]


In [102]:
#q12
array1=np.array([[0,1],[2,3]])
array2=np.array([[4,5],[6,7]])
array3=np.concatenate((array1,array2),axis=0)
print(array3)
array4=np.concatenate((array1,array2),axis=1)
print(array4)
array5=np.concatenate((array4,array4),axis=0)
print(array5)
array6=np.concatenate((array5,array5),axis=1)
print(array6)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5 0 1 4 5]
 [2 3 6 7 2 3 6 7]
 [0 1 4 5 0 1 4 5]
 [2 3 6 7 2 3 6 7]]


In [104]:
#Q13
#arr = np.array([[1, 2], [3, 4]])
#eg:result = np.tile(arr, (2, 3))
'''[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]'''

k=np.array(['_','*'])
res=np.tile(k,(5,5))
print(res)

[['_' '*' '_' '*' '_' '*' '_' '*' '_' '*']
 ['_' '*' '_' '*' '_' '*' '_' '*' '_' '*']
 ['_' '*' '_' '*' '_' '*' '_' '*' '_' '*']
 ['_' '*' '_' '*' '_' '*' '_' '*' '_' '*']
 ['_' '*' '_' '*' '_' '*' '_' '*' '_' '*']]


In [107]:
#q14
random_array = np.random.randint(0, 100, size=(5, 5))
print("Array:\n", random_array)
counts = np.bincount(random_array.flatten())
print("Counts:\n",counts)

Array:
 [[72 46 11 62 39]
 [39 13 43 26 38]
 [41 50 11 11 53]
 [ 6 13 67 94 11]
 [57 25 84 94 21]]
Counts:
 [0 0 0 0 0 0 1 0 0 0 0 4 0 2 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 1 2 0 1 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 2]


In [108]:
#q15
def median(arr):
    return np.median(arr)

def mode(arr):
    values, counts = np.unique(arr, return_counts=True)
    m = counts.argmax()
    return values[m]

# Test the functions
arr1 = np.random.randint(0, 10, size=(5, 5))
arr2 = np.random.randint(0, 10, size=(3, 3))
arr3 = np.random.randint(0, 10, size=(7, 7))

print("Median of arr1:\n", median(arr1))
print("Mode of arr1:\n", mode(arr1))

print("Median of arr2:\n", median(arr2))
print("Mode of arr2:\n", mode(arr2))

print("Median of arr3:\n", median(arr3))
print("Mode of arr3:\n", mode(arr3))


Median of arr1:
 5.0
Mode of arr1:
 2
Median of arr2:
 4.0
Mode of arr2:
 4
Median of arr3:
 4.0
Mode of arr3:
 3


In [112]:
#q16
array = np.random.rand(9, 9, 2)
sub_array = array[:5, :5, :]
print(sub_array)


[[[0.01137081 0.30025362]
  [0.81596795 0.84305535]
  [0.82134249 0.94711267]
  [0.95847274 0.18539995]
  [0.2624522  0.39958762]]

 [[0.3022895  0.68026786]
  [0.92153819 0.42308454]
  [0.54658232 0.42602875]
  [0.7235171  0.37427844]
  [0.48955627 0.89898291]]

 [[0.69424276 0.55815965]
  [0.31671026 0.48293443]
  [0.75461215 0.2801082 ]
  [0.90784017 0.15930246]
  [0.79717169 0.35155414]]

 [[0.65421966 0.91568112]
  [0.60906271 0.04577554]
  [0.49942907 0.78134823]
  [0.20196341 0.40471554]
  [0.18811977 0.86630574]]

 [[0.14322111 0.11195452]
  [0.53334457 0.06587777]
  [0.83806816 0.61807662]
  [0.62043974 0.01297679]
  [0.47796691 0.21471653]]]


In [110]:
#qq17
array = np.random.rand(4, 4)
sorted_array = np.sort(array, axis=0)
print(sorted_array)


[[0.14954512 0.48912987 0.14490572 0.40314667]
 [0.6333052  0.62139194 0.15413057 0.76065551]
 [0.79807352 0.92754436 0.25163666 0.87766962]
 [0.99252104 0.96686982 0.60266916 0.97770394]]


In [113]:
#q18
import pandas as pd

data = {
    'Column1': [1, 2, 3, 4],
    'Column2': [5, 6, 7, 8]
}
df = pd.DataFrame(data)
series = df['Column1']
print(series)


0    1
1    2
2    3
3    4
Name: Column1, dtype: int64


In [114]:
#q19
import pandas as pd

# Convert lists to Series
s1 = pd.Series([1, 2, 3, 4, 2])
s2 = pd.Series([3, 4, 5, 6])

# Find elements in s1 not in s2
result = s1[~s1.isin(s2)]
print(result)


0    1
1    2
4    2
dtype: int64


In [117]:
#q20
# Given series
s = pd.Series([1, 1, 3, 7, 88, 12, 88, 23, 3, 1, 9, 0])

# Find index of first occurrence of smallest and largest value
min_index = s.idxmin()
max_index = s.idxmax()
print(f"Index of smallest value: {min_index}")
print(f"Index of largest value: {max_index}")


Index of smallest value: 11
Index of largest value: 4


In [116]:
#q21
# Given list
L = ['Cry', 'Apple', 'Orange', 'Sky', 'Banana']

# Convert list to Series
s = pd.Series(L)

# Elements with a vowel
vowel_series = s[s.str.contains(r'[aeiouAEIOU]')]
print("Series with vowels:", vowel_series)

# Elements starting with a vowel
start_vowel_series = s[s.str.match(r'^[aeiouAEIOU]')]
print("Series starting with a vowel:", start_vowel_series)


Series with vowels: 1     Apple
2    Orange
4    Banana
dtype: object
Series starting with a vowel: 1     Apple
2    Orange
dtype: object


In [118]:
#q22
#a
series_a = pd.Series([7, 11, 13, 17])
print(series_a)
#b
series_b = pd.Series([100.0] * 5)
print(series_b)
#c
import numpy as np

series_c = pd.Series(np.random.randint(0, 100, size=20))
print(series_c.describe())
#d
temperatures = pd.Series([98.6, 98.9, 100.2, 97.9], index=['Julie', 'Charlie', 'Sam', 'Andrea'])
print(temperatures)
 #e
temp_dict = {'Julie': 98.6, 'Charlie': 98.9, 'Sam': 100.2, 'Andrea': 97.9}
series_d = pd.Series(temp_dict)
print(series_d)



0     7
1    11
2    13
3    17
dtype: int64
0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
dtype: float64
count    20.000000
mean     41.150000
std      25.452277
min       9.000000
25%      21.000000
50%      30.500000
75%      62.250000
max      89.000000
dtype: float64
Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64
Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64


In [ ]:
#Q23

#a
temp_dict = {
    'Maxine': [96.5, 98.2, 97.8],
    'James': [99.1, 98.3, 98.7],
    'Amanda': [97.8, 98.1, 98.5]
}
temperatures_df = pd.DataFrame(temp_dict)
print(temperatures_df)
print()

#b
temperatures_df = pd.DataFrame(temp_dict, index=['Morning', 'Afternoon', 'Evening'])
print(temperatures_df)
print()

#c
maxine_temps = temperatures_df['Maxine']
print(maxine_temps)
#d
morning_temps = temperatures.iloc[0]
print(morning_temps)

#e
morning_evening_temps = temperatures[0: 2]
print(morning_evening_temps)

#f
amanda_maxine_temps = temperatures[['Amanda', 'Maxine']]
print(amanda_maxine_temps)

#g
specific_temps = temperatures.loc[['Morning', 'Afternoon'], ['Amanda', 'Maxine']]
print(specific_temps)

#h
temp_stats = temperatures.describe()
print(temp_stats)
  

#i
transposed_temps = temperatures.T
print(transposed_temps)

#j
sorted_temps = temperatures[sorted(temperatures.columns)]
print(sorted_temps)


   Maxine  James  Amanda
0    96.5   99.1    97.8
1    98.2   98.3    98.1
2    97.8   98.7    98.5

           Maxine  James  Amanda
Morning      96.5   99.1    97.8
Afternoon    98.2   98.3    98.1
Evening      97.8   98.7    98.5

Morning      96.5
Afternoon    98.2
Evening      97.8
Name: Maxine, dtype: float64
98.6
Julie      98.6
Charlie    98.9
dtype: float64


KeyError: "None of [Index(['Amanda', 'Maxine'], dtype='object')] are in the [index]"